### ISSUE TITLE
Update to 4.0.0 from 3.2.0 broke use of open() elsewhere in app

### ISSUE THREAD

**Issue by nickooolas** [janko-m/down#15]
I'm not sure if this is as much an issue with `down`, but more-so, a side-effect of not having used `  require 'open-uri'` wherever I had previously used `open(url_here)` methods within my app.

After running a `bundle update`, `down` was updated to 4.0.0, and then I noticed it was breaking unless I required `open-uri`.

Is it possible that previously, `down` was requiring this, but now doesn't?

Also, is it always necessary to `require 'open-uri'` when using `open()`?

**Comment by janko-m** [comment]
Thank you for reporting this. That was expected with the changes that happened in 4.0, because now the `Down::NetHttp` backend (the default one) is required dynamically, so that if you want to use a different backend you don't need to require it. Since the `Down::NetHttp` required `open-uri`, and it now wasn't required automatically, the `open-uri` standard library wasn't required either (which extends `Kernel#open` with the ability to accept URLs).

As I explained in the commit, this change wasn't worth it, so I reverted back the change and released Down 4.0.1 which brings back the old behaviour. You should still remember to always explicitly require the standard libraries that you use in your code, and not rely that other gems will require them, but at least this bugfix will prevent this issue from happening to other users.

To answer your last question, it is always necessary to `require "open-uri"` when using `open()` for downloading, as `open-uri` extends `open()` to accept URLs (normally it still exists, but it accepts only filenames and subprocesses). Also, though unrelated, it's safer to use `URI(url).open` instead of `open(url)`, see [this article](https://sakurity.com/blog/2015/02/28/openuri.html).
