### ISSUE TITLE
save the file

### ISSUE THREAD

**Issue by derrickcope** [janko-m/down#18]
I don't understand how to save the file or is it not designed to do that?

**Comment by janko-m** [comment]
@derrickcope It doesn't currently have that functionality, because it was never needed in Shrine (the project it originated from), but I always thought it should have it. At the moment the file is saved into a temporary location, but it doesn't yet have a way to specify permanent user-defined location.

I'll try to implement this later today or tomorrow, but for now you can use this:

```rb
tempfile = Down.download("...")
tempfile.close
FileUtils.mv tempfile.path, "/path/to/destination"
```

**Comment by derrickcope** [comment]
That would be great!  I managed to save it another way.
`tempfile = Down.open(uri, rewindable: false)
 File.open(filename, "wb") do |file|
    file.write(tempfile.read)
    tempfile.close
 end`
The only problem is it saves it in memory and then outputs to the file. How would I stream it directly to the saved file?
thanks

**Comment by janko-m** [comment]
@derrickcope `IO.copy_stream` is a wonderful method:

```rb
io = Down.open(uri, rewindable: false)
File.open(filename, "wb") do |file|
  IO.copy_stream(io, file)
  io.close
end 
```

or even shorter:

```rb
io = Down.open(uri, rewindable: false)
IO.copy_stream(io, filename)
io.close
```

**Comment by derrickcope** [comment]
Thanks
